model:
  model_name: chexnet
  model: model/densenet121.xml
  weights: model/densenet121.bin

engine:
  config: config/chexnet.yaml

compression:
  algorithms:
  - name: DefaultQuantization
    params:
      preset: mixed
      stat_subset_size: 100
