models:
  - name: chexnet

    launchers:
      - framework: dlsdk
        device: CPU

        model: model/densenet121.xml
        weights: model/densenet121.bin
        adapter: person_attributes

    datasets:
      - name: chestxray14
        annotation: annotations/chestxray14.pickle
        dataset_meta: annotations/chestxray14.json
        data_source: images
        reader: pillow_imread

        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
            use_pillow: True
            interpolation: BILINEAR

          - type: crop
            size: 224
            use_pillow: True

          - type: normalization
            std: 255

          - type: normalization
            mean: (0.485, 0.456, 0.406) 
            std: (0.229, 0.224, 0.225)

        metrics:
          - type: multi_accuracy
            label_map: label_map
